/**
 * Quizz Platform API
 * API for Quizz Platform with authentication, quiz management, AI question generation, and translations
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AnswerResponse } from './AnswerResponse';

export class QuestionResponse {
    'questionText'?: string;
    'answers'?: Array<AnswerResponse>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "questionText",
            "baseName": "questionText",
            "type": "string",
            "format": ""
        },
        {
            "name": "answers",
            "baseName": "answers",
            "type": "Array<AnswerResponse>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QuestionResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
