/**
 * Quizz Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnswerResponse } from './answerResponse';


export interface QuestionResponse { 
    questionText?: string;
    answers?: Array<AnswerResponse>;
}

