/**
 * Quizz Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QuizResponse { 
    id?: number;
    title?: string;
    description?: string;
    isPublic?: boolean;
    userId?: number;
    username?: string;
    createdAt?: string;
}

