/**
 * Quizz Platform API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QuizRequest { 
    title: string;
    description: string;
    isPublic: boolean;
}

