package com.quizzplatform.ia;

import com.quizzplatform.quizz.AnswerEntity;
import com.quizzplatform.quizz.QuestionEntity;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@Service
public class IaService {

    @Value("${mistral.api.key}")
    private String mistralApiKey;

    @Value("${mistral.api.url}")
    private String mistralApiUrl;

    private final RestTemplate restTemplate;

    public IaService(RestTemplate restTemplate) {
        this.restTemplate = restTemplate;
    }

    public List<QuestionEntity> generateQuestions(String topic, int count) {
        try {
            // Prepare the request to Mistral API
            String prompt = String.format("Generate %d multiple-choice questions about %s. " +
                    "Each question should have 4 answers with one correct answer marked. " +
                    "Return in JSON format with questions and answers.", count, topic);

            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            headers.setBearerAuth(mistralApiKey);

            Map<String, Object> requestBody = Map.of(
                    "model", "mistral-tiny",
                    "messages", List.of(Map.of("role", "user", "content", prompt)),
                    "temperature", 0.7
            );

            HttpEntity<Map<String, Object>> request = new HttpEntity<>(requestBody, headers);

            // Call Mistral API
            ResponseEntity<Map> response = restTemplate.postForEntity(
                    mistralApiUrl + "/chat/completions", 
                    request, 
                    Map.class
            );

            // Parse the response and create QuestionEntity objects
            return parseMistralResponse(response.getBody());
        } catch (Exception e) {
            // Fallback: generate sample questions if API fails
            return generateSampleQuestions(topic, count);
        }
    }

    private List<QuestionEntity> parseMistralResponse(Map<String, Object> response) {
        // In a real implementation, you would parse the Mistral API response
        // For now, return sample data
        List<QuestionEntity> questions = new ArrayList<>();
        
        // This is a placeholder - actual implementation would parse the API response
        QuestionEntity question = new QuestionEntity();
        question.setQuestionText("Sample question generated by Mistral API");
        
        List<AnswerEntity> answers = new ArrayList<>();
        AnswerEntity answer1 = new AnswerEntity();
        answer1.setAnswerText("Answer 1");
        answer1.setCorrect(true);
        answers.add(answer1);
        
        AnswerEntity answer2 = new AnswerEntity();
        answer2.setAnswerText("Answer 2");
        answer2.setCorrect(false);
        answers.add(answer2);
        
        question.setAnswers(answers);
        questions.add(question);
        
        return questions;
    }

    private List<QuestionEntity> generateSampleQuestions(String topic, int count) {
        List<QuestionEntity> questions = new ArrayList<>();
        for (int i = 0; i < count; i++) {
            QuestionEntity question = new QuestionEntity();
            question.setQuestionText("Sample question " + (i + 1) + " about " + topic);
            
            List<AnswerEntity> answers = new ArrayList<>();
            for (int j = 0; j < 4; j++) {
                AnswerEntity answer = new AnswerEntity();
                answer.setAnswerText("Answer " + (j + 1));
                answer.setCorrect(j == 0); // First answer is correct
                answers.add(answer);
            }
            question.setAnswers(answers);
            questions.add(question);
        }
        return questions;
    }
}